# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6044143a2bd1b905da1f6907eb5ab3d20fae3cd84e2b3a3e1ad3b1d27626623da1972176703e48a1db2b78b352edcdaceb8f2fd0c108002a2af00011823d8b76

test:
  secret_key_base: 0e75d64244dcd69a31f4280857455f02348ca51d29b018d1b54d4469c66cc96afe3b563ebd6b73fa8138abf022e18485c6c802c4dd361717b1dcbce208c0a3cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
